spring.application.name=JavaSpring

# DATABASE
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/javaspring_db;MODE=PostgreSQL;AUTO_SERVER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fitiavanaras0@gmail.com
spring.mail.password=ncjutgcovqacwgno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=https://silvia-pencillike-subterraneanly.ngrok-free.dev

# JWT
jwt.secret=acxNIPNa2dxospL2sqpNysaXf183fPmfdbpUU7g8SFU=
jwt.expiration=86400000

#AES
app.aes.key=1234567890123456
